filrouge DWWM/src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OperationRepository::class)
 */
class Operation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Email
     */
    private $email_user;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_command;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Email
     */
    private $email_customer;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $type_operation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_customer;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmailUser(): ?string
    {
        return $this->email_user;
    }

    public function setEmailUser(string $email_user): self
    {
        $this->email_user = $email_user;

        return $this;
    }

    public function getNumCommand(): ?int
    {
        return $this->num_command;
    }

    public function setNumCommand(int $num_command): self
    {
        $this->num_command = $num_command;

        return $this;
    }

    public function getEmailCustomer(): ?string
    {
        return $this->email_customer;
    }

    public function setEmailCustomer(string $email_customer): self
    {
        $this->email_customer = $email_customer;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTypeOperation(): ?string
    {
        return $this->type_operation;
    }

    public function setTypeOperation(string $type_operation): self
    {
        $this->type_operation = $type_operation;

        return $this;
    }


    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getNameCustomer(): ?string
    {
        return $this->name_customer;
    }

    public function setNameCustomer(string $name_customer): self
    {
        $this->name_customer = $name_customer;

        return $this;
    }

}

filrouge DWWM/src/Form/OperationType.php
<?php

namespace App\Form;

use App\Entity\Operation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class OperationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_customer')
            ->add('email_user')
            ->add('num_command')
            ->add('email_customer')
            ->add('description', TextareaType::class, ['attr' => ['class' => "description"]])
            ->add('type_operation', ChoiceType::class, ['choices' => [

                'PETITE' => 'PETITE',
                'MOYENNE' => 'MOYENNE',
                'GROSSE' => 'GROSSE'
            ]]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Operation::class,
        ]);
    }
}

filrouge DWWM/src/Controller/OperationController.php
<?php

namespace App\Controller;

use App\Entity\Command;
use App\Entity\Operation;
use App\Form\OperationType;
use App\Repository\OperationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OperationController extends AbstractController
{

    /**
     * @Route("/operation/statut/{id}", name="op_terminee")
     */
    public function operationTerminee(Operation $operation, EntityManagerInterface $manager, Request $request): Response
    {
        dump($operation);
        if ($this->isCsrfTokenValid("SUP" . $operation->getId(), $request->get('_token'))) {

            $operation->setStatut('T');
            $manager->persist($operation);
            // $manager->remove($type);
            $manager->flush();
            $this->addFlash('success', "L'opération est terminée");

            return $this->redirectToRoute('liste_operations');
        }
    }

    /**
     * @Route("/operation/{id}", name="add_operation")
     */
    public function operation(Operation $operation = null, Command $command, Request $request, EntityManagerInterface $manager, OperationRepository $repo): Response
    {

        // $operation = new Operation();
        // $operation->setStatut('Terminer');

        if (!$operation) {
            $operation = new Operation();
            $operation->setStatut('C');
        } else {
            $operation->setStatut('T');
        }
        
        //CODE ASSIA
        $operationsEnCours = $repo->findOperationEncours();
        $profil = $this->getUser()->getProfil();
        $mail = $this->getUser()->getEmail();
        $compteur = 0;

        foreach ($operationsEnCours as $key => $value) {
            if ($value->getEmailUser() == $mail) {
                $compteur++;
            };
        }


        // dd($compteur);

        if ($profil === "EXPERT" and $compteur < 5) {

            $form = $this->createForm(OperationType::class, $operation);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $manager->remove($command);
                $manager->persist($operation);
                $manager->flush();
                $this->addFlash('success', "L'ajout a bien été réalisé");

                return $this->redirectToRoute('liste_operations');
            }

            return $this->render('operation/addOperation.html.twig', [
                'command' => $command,
                'form' => $form->createView(),
            ]);
        } elseif (($profil === "SENIOR" and $compteur < 3)) {


            $form = $this->createForm(OperationType::class, $operation);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $manager->remove($command);
                $manager->persist($operation);
                $manager->flush();
                $this->addFlash('success', "L'ajout a bien été réalisée");

                return $this->redirectToRoute('liste_operations');
            }

            return $this->render('operation/addOperation.html.twig', [
                'command' => $command,
                'form' => $form->createView(),
            ]);
        } elseif (($profil === "APPRENTI" and $compteur < 1)) {


            $form = $this->createForm(OperationType::class, $operation);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                //$manager->remove($command);
                $manager->persist($operation);
                $manager->flush();
                $this->addFlash('success', "L'ajout a bien été réalisée");

                return $this->redirectToRoute('liste_operations');
            }

            return $this->render('operation/addOperation.html.twig', [
                'command' => $command,
                'form' => $form->createView(),
            ]);
        } else {
            $this->addFlash('wrong', "Vous ne pouvez pas ajouter d'autres opérations. Vous avez dépassé le nombre autorisé. Veuillez finaliser vos opérations existantes.");
            return $this->redirectToRoute('recapCommand');
        }
    }

    /**
     * @Route("/operation", name="liste_operations")
     */
    public function listeOperations(OperationRepository $repo): Response
    {
        // dump();
        $operations = $repo->findAll();
        $operationsEnCours = $repo->NombreOperationEncours();

        return $this->render('operation/listeOperations.html.twig', [
            'operations' => $operations,
            'operationsEnCours' => $operationsEnCours,
        ]);
    }
}

filrouge DWWM/templates/operation/addOperation.html.twig
{% extends "dashboard/expertDashboard.html.twig" %}


{% block title %}Ajout opérations
{% endblock %}


{% block col_content %}


    {{ form_start(form,  {'attr': {'class' : "mx-auto mt-5"}}) }}


	{{ form_row(form.email_user, {'label': 'Email operateur', 'attr': {'value': (app.user.email), 'readonly': true, 'class' : "text-primary" }}) }}

	{{ form_row(form.name_customer, {'label': 'Nom Client', 'attr': {'value': (command.nameCustomer), 'readonly': true}}) }}

	{{ form_row(form.num_command, {'label': 'Numero commande', 'attr': {'value': (command.id), 'readonly': true}}) }}

	{{ form_row(form.email_customer, {'label': 'Email client', 'attr': {'value': (command.emailCustomer), 'readonly': true }}) }}


	{{ form_row(form.description, {'attr': {'value': (command.description), 'placeholder': (command.description), 'readonly': true }}) }}

	{{ form_row(form.type_operation) }}


        <div class="form-group d-flex mt-2 float-end">
            <button name="submit" type="submit" class="btn btn-secondary" id="ajout"> Ajouter </button>
            <a href="{{ path('dashboard') }}" class="btn btn-secondary  ms-5">Annuler</a>
        </div>
    {{ form_end(form) }}



{% endblock %}

filrouge DWWM/templates/operation/listeOperations.html.twig
{% extends "dashboard/expertDashboard.html.twig" %}

{% block title %}Mes opérations
{% endblock %}

{% block col_content %}

	<div class="row">
		<div class="row">
			<div class="col-8">
				<h1 class="text-primary d-inline">Mes opérations en cours...</h1>
			</div>
			<div class="col d-flex align-items-center">
				{% for message in app.flashes('success') %}
					<h5 class="text-success" id="error">
						✓
						{{ message }}</h5>
				{% endfor %}
			</div>
		</div>
		{% for operation in operations %}
			{% if (app.user.email == operation.emailUser) and (operation.statut == 'C') %}
				<div class="col-12 col-md-6 col-lg-4 col-xl-3">
					<div class="card mb-3 mx-auto" style="max-width:20rem">
						<div class="card-header text-center">
							<h4 class="text-center" style="color:#939595b4">Commande n°{{ operation.numCommand  }}</h4>
						</div>
						<div class="card-body text-center">

							<form method="POST" action="{{ path('op_terminee', {'id' : operation.id}) }}" style="display:inline-block;">
								<input type="hidden" name="_method" value="SUP"/>
								<input type="hidden" name="_token" value="{{ csrf_token("SUP" ~ operation.id) }}">
								<input type="submit" class="btn btn-success" value="Terminer"/>
							</form>
						</div>
					</div>
				</div>
				{# <tr class="text-primary menu-nav">    																																																																													                </tr> #}
			{% endif %}
		{% endfor %}
	</div>

	<hr style="color:blue ; height:3px">
	<hr style="color:white ; height:3px">
	<hr style="color:red ; height:3px">
	<div class="row">
		<h1 class="text-primary">Mes opérations terminées</h1>
		{% for operation in operations %}
			{% if (app.user.email == operation.emailUser) and (operation.statut == 'T')  %}
				<div class="col-12 col-md-6 col-lg-4 col-xl-3">
					<div class="card mb-3 mx-auto" style="max-width:20rem">
						<div class="card-header text-center">
							<h4 class="text-center" style="color:#939595b4">Commande n°{{ operation.numCommand  }}</h4>
						</div>
						<div class="card-body text-center" style="display:flex ; justify-content:center">
							<form method="POST" action="{{path("app_pdf_generator", {'id' : operation.id}) }}" style="display:inline-block ; padding: 2px">
								<input type="submit" class="btn btn-success" value="Télécharger PDF"/>
							</form>
							<form method="" action="{{path("app_mailer")}}" style="display:inline-block; padding: 2px">
								<input type="submit" class="btn btn-success" value="Mail au client"/>
							</form>
						</div>
					</div>
				</div>
			{% endif %}
		{% endfor %}
	</div>
{% endblock %}